language: cpp

addons:
  homebrew:
    update: true
    brewfile: true

matrix:
  include:
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-toolchain-trusty-5.0
    #       packages:
    #         - clang-5.0
    #         - libuv-dev
    #         - libc++
    #   env:
    #     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    #   before_install:
    #     - eval "${MATRIX_EVAL}"

    - os: osx
script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j
  - make test
